### ISSUE TITLE
Get Calendar Access

### ISSUE THREAD

**Issue by stevemacn** [uncCharlotteHCI/unccharlottehci.github.io#15]
We need to have calendar access for all students. Invite all students to the calendar so that they can edit the calendar and add events.

**Comment by stevemacn** [comment]
Access should be provided to: MJ, Nasheen, Sarah, Johanna.

**Comment by jyxia** [comment]
I have sent the invitations to everyone.

**Comment by stevemacn** [comment]
Great! Thanks @jyxia
